version: '3.7'

services:
  haproxy:
    build: ./haproxy
    volumes:
      - ./haproxy/certs:/etc/haproxy/certs  # Mount the local certs directory
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mosowo_com
      - mosowo_net
    networks:
      mosowo_network:
        ipv4_address: 172.28.1.2

  mosowo_com:
    build: ./mosowo_com
    ports:
      - "3000:3000"
    networks:
      mosowo_network:
        ipv4_address: 172.28.1.3

  mosowo_net:
    build: ./mosowo_net
    ports:
      - "3001:3001"
    networks:
      mosowo_network:
        ipv4_address: 172.28.1.4

networks:
  mosowo_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
